# Generated by Django 2.1.5 on 2019-04-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190329_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('F', 'Favorite'), ('M', 'MATCH'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('M', 'Matched'), ('C', 'Commented'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('S', 'Also Commented')], max_length=8),
        ),
    ]
