# Generated by Django 2.1.5 on 2019-04-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190406_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='currentbreed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
