# Generated by Django 2.1.5 on 2019-06-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('animal_type', models.CharField(choices=[('cow', 'cow'), ('pig', 'pig')], default='cow', max_length=50)),
                ('breed_type', models.CharField(choices=[('ankole', 'ankole'), ('jersey', 'jersey'), ('zebu', 'zebu'), ('fresian', 'fresian'), ('unknown', 'unknown'), ('guernsey', 'guernsey'), ('berkishire', 'berkishire'), ('cambra', 'cambra'), ('duroc', 'duroc'), ('hampshire', 'hampshire'), ('kunekune', 'kunekune'), ('landrace', 'landrace'), ('largeblack', 'largeblack'), ('largewhite', 'largewhite'), ('lberian', 'lberian'), ('redhog', 'redhog'), ('saddleback', 'saddleback')], default='unknown', max_length=50)),
                ('breed', models.TextField(max_length=255)),
                ('matches', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=8)),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='breeds', verbose_name='photo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='breeds.Breed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breed',
                'ordering': ('rating',),
            },
        ),
    ]
