# Generated by Django 2.1.5 on 2019-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='animal_type',
            field=models.CharField(choices=[('cow', 'cow'), ('pig', 'pig')], default='unknown', max_length=50),
        ),
    ]
