# Generated by Django 2.1.5 on 2019-03-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_auto_20190329_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breed_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=8),
        ),
    ]
