# Generated by Django 2.1.5 on 2019-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_breed_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='accuracy',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(choices=[('ankole', 'ankole'), ('jersey', 'jersey'), ('zebu', 'zebu'), ('fresian', 'fresian'), ('unknown', 'unknown')], default='cow', max_length=50),
        ),
    ]
