# Generated by Django 2.1.5 on 2019-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0003_auto_20190430_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='animal_type',
            field=models.CharField(choices=[('COW', 'Cow'), ('PIG', 'Pig')], default='COW', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(choices=[('ANKOLE', 'Ankole'), ('JERSEY', 'Jersey'), ('ZEBU', 'Zebu'), ('FRESIAN', 'Fresian'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
