# Generated by Django 2.1.5 on 2019-04-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0003_breed_breed_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='likes',
            new_name='matches',
        ),
    ]
