# Generated by Django 2.2.1 on 2019-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0004_auto_20190430_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='breed',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
