# Generated by Django 2.1.5 on 2019-04-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0005_breed_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='breeds', verbose_name='photo'),
        ),
    ]
