# Generated by Django 2.2.1 on 2019-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0005_auto_20190528_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('rating',), 'verbose_name': 'Breed', 'verbose_name_plural': 'Breed'},
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(choices=[('ankole', 'ankole'), ('jersey', 'jersey'), ('zebu', 'zebu'), ('fresian', 'fresian'), ('unknown', 'unknown'), ('guernsey', 'guernsey'), ('berkishire', 'berkishire'), ('cambra', 'cambra'), ('duroc', 'duroc'), ('hampshire', 'hampshire'), ('kunekune', 'kunekune'), ('landrace', 'landrace'), ('largeblack', 'largeblack'), ('largewhite', 'largewhite'), ('lberian', 'lberian'), ('redhog', 'redhog'), ('saddleback', 'saddleback')], default='unknown', max_length=50),
        ),
    ]
