# Generated by Django 2.1.5 on 2019-04-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0006_breed_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='breed_sex',
            new_name='sex',
        ),
    ]
