# Generated by Django 2.1.5 on 2019-04-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0007_auto_20190406_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=8),
        ),
    ]
