# Generated by Django 2.1.5 on 2019-04-11 08:25

import django.contrib.gis.geos.point
from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0009_auto_20190406_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='location',
            field=geoposition.fields.GeopositionField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), max_length=42),
        ),
    ]
