# Generated by Django 2.1.5 on 2019-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0011_auto_20190411_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
