# Generated by Django 2.1.5 on 2019-04-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0012_breed_breed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='location',
        ),
    ]
