# Generated by Django 2.1.5 on 2019-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0013_remove_breed_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
