# Generated by Django 2.1.5 on 2019-04-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0014_auto_20190412_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_type',
            field=models.CharField(choices=[('ANKOLE', 'Ankole'), ('JERSEY', 'Jersey'), ('ZEBU', 'Zebu'), ('FRESIAN', 'Fresian'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
