# Generated by Django 2.1.5 on 2019-04-06 18:29

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190406_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326),
        ),
    ]
