# Generated by Django 2.1.5 on 2019-04-11 08:26

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190411_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
